version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myfaztdb
      SPRING_DATASOURCE_USERNAME: fazt
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: some-postgres
    environment:
      POSTGRES_USER: fazt
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: myfaztdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
