server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myfaztdb
    username: fazt
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis

  redis:
    host: redis # Nombre del contenedor de Redis en Docker
    port: 6379
